"""Add FK from Tutor.user_id to User.id

Revision ID: 02ce3a95022b
Revises: 43648bd833d9
Create Date: 2025-07-01 12:19:22.666105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02ce3a95022b'
down_revision = '43648bd833d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tutors', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tutors', type_='foreignkey')
    # ### end Alembic commands ### 